name: Release and Publish to NPM

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  release:
    name: Release and Publish

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM Dependencies
        run: npm install

      - name: Build
        run: npm run webpack

      - name: Publish Types to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}