on:
  pull_request:
    
jobs:
  release:
    name: Test runner
    runs-on: ubuntu-latest
    environment: OSSBLD
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: npm ci
      - run: npm run test
        env:
          VITE_SERVER: ${{ secrets.VITE_SERVER }}
          VITE_PORT: ${{ secrets.VITE_PORT }}
          VITE_DB_USER: ${{ secrets.VITE_DB_USER }}
          VITE_DB_PASS: ${{ secrets.VITE_DB_PASS }}